location / {
    if ($http_origin ~* "^https?://(localhost:3000|brave-desert-074ebc30f.4.azurestaticapps.net)$") {
        add_header Access-Control-Allow-Origin "$http_origin";
        add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization, X-TESTER-REQUEST' always;
    }

    if ($request_method = 'OPTIONS') {
        return 204;
    }
    #For testing comment
    proxy_pass          http://127.0.0.1:5000;
    proxy_http_version  1.1;

    proxy_set_header    Connection          $connection_upgrade;
    proxy_set_header    Upgrade             $http_upgrade;
    proxy_set_header    Host                $host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

    proxy_hide_header   Access-Control-Allow-Origin;
    proxy_hide_header   Access-Control-Allow-Methods;
    proxy_hide_header   Access-Control-Allow-Headers;
}