#There's no DEV profile, this is basically the dev profile, prod profile overrides the required config
caffeine:
  maxWeight: 100

rateLimiter:
  bandwidth: 20

spring:
  ai:
    voyager:
      api-key: "pa-yUOVox6UfNrtdGoJKJCVEUa4DN3gvkIRirwEoXwwR5m"
      model: "voyage-3"
    vector-store:
      mongodb:
        path-name: "embedding"
    open-router:
      api-key: "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"
      url: "https://openrouter.ai"
      chat-completions: "/api/v1/chat/completions"

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23limRtEf8mTb5Gb3v
            client-secret: f2ee8b8514afa79bf19ce15176ebe0cba1bb1304
            scope: read:user,user:email
          google:
            client-id: 509576134964-m14iac1flght5q8glb1ak03k9h2mokml.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile

auth:
  redirect: "http://localhost:3000/status"
logging:
  filename: ipos.log
  dir: ./
  level:
    org:
      springframework:
        security: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always
