spring.application.name=ipos
server.servlet.context-path=/service

server.port=8080
spring.data.mongodb.uri.base=mongodb+srv://adminuser:3jfe0FxS41OwumgZ@cluster0.jqvde.mongodb.net
security.disable=false