server:
  port: 5000 #Elastic bean stalk opens port 80 and redirect to 5000 using nginx by default
  forward-headers-strategy: native
  tomcat:
    protocol-header: x-forwarded-proto
    protocol-header-https-value: https


logging:
  dir: /var/app/current/logs #/var/app/current is the directory the beanstalk gives the webapp user access to
  level:
    org:
      springframework:
        security: TRACE #INFO, DEBUG, TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lisJE4TPh82zuAj6
            client-secret: 3d4068c8c5439a819647f4d4c9c0717f0a7109ca
            scope: read:user,user:email