spring.application.name=mail
server.servlet.context-path=/notification
server.port=${APPLICATION_PORT:9000}

#To completely disable ssl verification set this to false
server.ssl.enabled=true

#To only use 1 way ssl comment this line
server.ssl.client-auth=need

server.ssl.key-store=classpath:usernotif_keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mail
server.ssl.key-store-password=6381075249

server.ssl.trust-store=classpath:truststore.p12
server.ssl.trust-store-password=6381075249
server.ssl.trust-store-type=PKCS12

logging.level.org.apache.tomcat.util.net=DEBUG
