name: AWS EBS Spring Backend

on:
  push:
    branches:
      - deploy/backend
  pull_request:
    types: [closed]
    branches:
      - deploy/backend
env:
  PROJECT_LOCATION: services/ipos
  ELASTIC_BEANSTALK_NAME: ipos_backend
  ELASTIC_BEANSTALK_ENV_NAME: Iposbackend-env-2
  JAR_NAME: ipos-0.0.1-SNAPSHOT.jar #Once you hit a stable release increment major,minor,path with the versions so the S3 bucket contains older version for rollback

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: cd $PROJECT_LOCATION && mvn clean install -Dspring.profiles.active=prod -Dmaven.test.skip=true
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-southeast-1
        aws-access-key-id: ${{ secrets.BEANSTALK_AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BEANSTALK_AWS_SECRET_KEY }}
    - name: Deploy
      run: |
        cd $PROJECT_LOCATION/target && aws s3 cp $JAR_NAME s3://elasticbeanstalk-ap-southeast-1-961341514752/artifact/spring-app/ || exit 1
        aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-ap-southeast-1-961341514752",S3Key="artifact/spring-app/$JAR_NAME" || exit 1
        aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label ${{github.run_id}} || exit 1
  